name: Authenticate to GCP

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows you to manually trigger it from GitHub UI

permissions:
  id-token: write
  contents: read

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/827812434085/locations/global/workloadIdentityPools/github/providers/github-provider
          service_account: github-actions-sa@direct-outlet-458407-n6.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true
          universe: googleapis.com
          cleanup_credentials: true
          access_token_lifetime: 3600s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
